"""Added GeoAlchemy2 support to points table

Revision ID: 640de7aafac2
Revises: 00442761c803
Create Date: 2026-08-21 13:12:18.083709

"""

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "640de7aafac2"
down_revision = "00442761c803"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("points", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "point",
                geoalchemy2.types.Geography(geometry_type="POINT", srid=4326),
                nullable=True,
            )
        )

    op.execute(sa.text("""
            UPDATE points
            SET point = ST_SetSRID(
                ST_MakePoint(COALESCE(longitude, 0), COALESCE(latitude, 0)),
                4326
            )::geography
            """))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("points", schema=None) as batch_op:
        batch_op.drop_column("point")

    # ### end Alembic commands ###
